// <auto-generated />
using System;
using ISync.Classes.Core.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ISync.Migrations
{
    [DbContext(typeof(MovimentacaoContext))]
    partial class MovimentacaoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Cobranca.Dup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DVenc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DetPagId")
                        .HasColumnType("int");

                    b.Property<int>("FatId")
                        .HasColumnType("int");

                    b.Property<string>("NDup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SysDInsert")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SysDUpdate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SysIsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("VDup")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DetPagId");

                    b.HasIndex("FatId");

                    b.ToTable("tbMovDups", (string)null);
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Cobranca.Fat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("IdeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IdeId1")
                        .HasColumnType("int");

                    b.Property<string>("NFat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SysDInsert")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SysDUpdate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SysIsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal?>("VDesc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VLiq")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VOrig")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdeId1");

                    b.ToTable("tbMovFats", (string)null);
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Cobranca.FatPagProd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FatId")
                        .HasColumnType("int");

                    b.Property<int>("ProdId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SysDInsert")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SysDUpdate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SysIsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal?>("VAcresc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VDesc")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FatId");

                    b.ToTable("FatPagProd");
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Destinatario.Dest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CMun")
                        .HasColumnType("bigint");

                    b.Property<int?>("CPais")
                        .HasColumnType("int");

                    b.Property<Guid>("CadastroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Fone")
                        .HasColumnType("bigint");

                    b.Property<string>("IE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISUF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdEstrangeiro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IdeId1")
                        .HasColumnType("int");

                    b.Property<int?>("IndIEDest")
                        .HasColumnType("int");

                    b.Property<string>("Nro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SysDInsert")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SysDUpdate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SysIsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XBairro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCpl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XLgr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XMun")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XPais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdeId1");

                    b.ToTable("tbMovDests", (string)null);
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Detalhe.DeclaracaoImportacao.Adi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CFabricante")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DIId")
                        .HasColumnType("int");

                    b.Property<int>("NAdicao")
                        .HasColumnType("int");

                    b.Property<string>("NDraw")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NSeqAdic")
                        .HasColumnType("int");

                    b.Property<DateTime>("SysDInsert")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SysDUpdate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SysIsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal?>("VDescDI")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DIId");

                    b.ToTable("tbMovProdDIAdis", (string)null);
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Detalhe.DeclaracaoImportacao.DI", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CExportador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DDI")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DDesemb")
                        .HasColumnType("datetime2");

                    b.Property<string>("NDI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProdId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SysDInsert")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SysDUpdate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SysIsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("TpIntermedio")
                        .HasColumnType("int");

                    b.Property<int>("TpViaTransp")
                        .HasColumnType("int");

                    b.Property<string>("UFDesemb")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UFTerceiro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("VAFRMM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("XLocDesemb")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProdId");

                    b.ToTable("tbMovProdDIs", (string)null);
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Detalhe.Exportacao.DetExport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NDraw")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProdId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SysDInsert")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SysDUpdate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SysIsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ProdId");

                    b.ToTable("tbMovProdDetExports", (string)null);
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Detalhe.Exportacao.ExportInd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChNFe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DetExportId")
                        .HasColumnType("int");

                    b.Property<string>("NRE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("QExport")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("SysDInsert")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SysDUpdate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SysIsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DetExportId");

                    b.ToTable("tbMovProdDetExportInds", (string)null);
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Detalhe.Prod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CBenef")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CEAN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CEANTrib")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CEST")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CFOP")
                        .HasColumnType("int");

                    b.Property<string>("CNPJFab")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CProd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Cancelado")
                        .HasColumnType("bit");

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("CategoriaNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EXTIPI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdeId")
                        .HasColumnType("int");

                    b.Property<int?>("IndEscala")
                        .HasColumnType("int");

                    b.Property<int>("IndTot")
                        .HasColumnType("int");

                    b.Property<string>("InfAdProd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NCM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NFCI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NItem")
                        .HasColumnType("int");

                    b.Property<int?>("NItemPed")
                        .HasColumnType("int");

                    b.Property<string>("NRECOPI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NVE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PTribEst")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PTribFed")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PTribMun")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProdutoGradeId")
                        .HasColumnType("int");

                    b.Property<decimal>("QCom")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("QTrib")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("SysDInsert")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SysDUpdate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SysIsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("UCom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UTrib")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("VCusto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VDesc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VFrete")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VOutro")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VProd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VSeg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VTotTrib")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VUnCom")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VUnTrib")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VendedorId")
                        .HasColumnType("int");

                    b.Property<string>("XPed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XProd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdeId");

                    b.ToTable("tbMovProds", (string)null);
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Detalhe.ProdEspecifico.Comb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CODIF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CProdANP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescANP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PGLP")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PGNi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PGNn")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PMixGN")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProdId")
                        .HasColumnType("int");

                    b.Property<decimal?>("QTemp")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("SysDInsert")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SysDUpdate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SysIsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("UFCons")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("VPart")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProdId");

                    b.ToTable("tbMovProdCombs", (string)null);
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Detalhe.ProdEspecifico.Encerrante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CombId")
                        .HasColumnType("int");

                    b.Property<int>("NBico")
                        .HasColumnType("int");

                    b.Property<int?>("NBomba")
                        .HasColumnType("int");

                    b.Property<int>("NTanque")
                        .HasColumnType("int");

                    b.Property<DateTime>("SysDInsert")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SysDUpdate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SysIsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("VEncFin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VEncIni")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CombId");

                    b.ToTable("tbMovProdCombEncerrantes", (string)null);
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Detalhe.Tributacao.Estadual.ICMS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CSOSN")
                        .HasColumnType("int");

                    b.Property<int>("CST")
                        .HasColumnType("int");

                    b.Property<int>("ModBC")
                        .HasColumnType("int");

                    b.Property<int>("ModBCST")
                        .HasColumnType("int");

                    b.Property<int?>("MotDesICMS")
                        .HasColumnType("int");

                    b.Property<int>("Orig")
                        .HasColumnType("int");

                    b.Property<decimal>("PBCOp")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PCredSN")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PDif")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PFCP")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PFCPST")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PFCPSTRet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PFCPUFDest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PICMS")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PICMSEfet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PICMSInter")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PICMSInterPart")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PICMSST")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PICMSUFDest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PMVAST")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PRedBC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PRedBCEfet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PRedBCST")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PST")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProdId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SysDInsert")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SysDUpdate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SysIsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("UFST")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("VBC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VBCEfet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VBCFCP")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VBCFCPST")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VBCFCPSTRet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VBCFCPUFDest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VBCST")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VBCSTDest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VBCSTRet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VBCUFDest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VCredICMSSN")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VFCP")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VFCPST")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VFCPSTRet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VFCPUFDest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VICMS")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VICMSDeson")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VICMSDif")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VICMSEfet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VICMSOp")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VICMSST")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VICMSSTDest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VICMSSTRet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VICMSSubstituto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VICMSUFDest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VICMSUFRemet")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProdId");

                    b.ToTable("tbMovProdIcms", (string)null);
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Detalhe.Tributacao.Federal.COFINS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CST")
                        .HasColumnType("int");

                    b.Property<decimal?>("PCOFINS")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProdId")
                        .HasColumnType("int");

                    b.Property<decimal?>("QBCProd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("SysDInsert")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SysDUpdate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SysIsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal?>("VAliqProd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VBC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VCOFINS")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProdId");

                    b.ToTable("tbMovProdCofins", (string)null);
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Detalhe.Tributacao.Federal.II", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProdId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SysDInsert")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SysDUpdate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SysIsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("VBC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VDespAdu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VII")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VIOF")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProdId");

                    b.ToTable("tbMovProdIis", (string)null);
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Detalhe.Tributacao.Federal.IPI", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CEnq")
                        .HasColumnType("int");

                    b.Property<string>("CNPJProd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CST")
                        .HasColumnType("int");

                    b.Property<string>("CSelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClEnq")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PIPI")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProdId")
                        .HasColumnType("int");

                    b.Property<int?>("QSelo")
                        .HasColumnType("int");

                    b.Property<decimal?>("QUnid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("SysDInsert")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SysDUpdate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SysIsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal?>("VBC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VIPI")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VUnid")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProdId");

                    b.ToTable("tbMovProdIpis", (string)null);
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Detalhe.Tributacao.Federal.PIS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CST")
                        .HasColumnType("int");

                    b.Property<decimal>("PPIS")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProdId")
                        .HasColumnType("int");

                    b.Property<decimal?>("QBCProd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("SysDInsert")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SysDUpdate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SysIsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal?>("VAliqProd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VBC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VPIS")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProdId");

                    b.ToTable("tbMovProdPis", (string)null);
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Detalhe.Tributacao.Municipal.ISSQN", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CListServ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("CMun")
                        .HasColumnType("bigint");

                    b.Property<long>("CMunFG")
                        .HasColumnType("bigint");

                    b.Property<int?>("CPais")
                        .HasColumnType("int");

                    b.Property<string>("CServico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IndISS")
                        .HasColumnType("int");

                    b.Property<int?>("IndIncentivo")
                        .HasColumnType("int");

                    b.Property<string>("NProcesso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProdId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SysDInsert")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SysDUpdate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SysIsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("VAliq")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VBC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VDeducao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VDescCond")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VDescIncond")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VISSQN")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VISSRet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VOutro")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProdId");

                    b.ToTable("tbMovProdISSQNs", (string)null);
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Emitente.Emit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CMun")
                        .HasColumnType("bigint");

                    b.Property<string>("CNAE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CPais")
                        .HasColumnType("int");

                    b.Property<int>("CRT")
                        .HasColumnType("int");

                    b.Property<string>("Doc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<long?>("Fone")
                        .HasColumnType("bigint");

                    b.Property<string>("IE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IEST")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdeId")
                        .HasColumnType("int");

                    b.Property<string>("Nro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SysDInsert")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SysDUpdate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SysIsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XBairro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCpl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XFant")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XLgr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XMun")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XPais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdeId");

                    b.ToTable("tbMovEmits", (string)null);
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Identificacao.Ide", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CDV")
                        .HasColumnType("int");

                    b.Property<long>("CMunFG")
                        .HasColumnType("bigint");

                    b.Property<string>("CNF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CUF")
                        .HasColumnType("int");

                    b.Property<int>("ContratoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DCompetencia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DhCont")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DhEmi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DhSaiEnt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<int>("FinNFe")
                        .HasColumnType("int");

                    b.Property<int?>("IdDest")
                        .HasColumnType("int");

                    b.Property<string>("IdNFe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IndFinal")
                        .HasColumnType("int");

                    b.Property<int?>("IndIntermed")
                        .HasColumnType("int");

                    b.Property<int?>("IndPag")
                        .HasColumnType("int");

                    b.Property<int?>("IndPres")
                        .HasColumnType("int");

                    b.Property<string>("InfAdFisco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InfCpl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Mod")
                        .HasColumnType("int");

                    b.Property<long>("NNF")
                        .HasColumnType("bigint");

                    b.Property<string>("NatOp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OperadorId")
                        .HasColumnType("int");

                    b.Property<int>("ProcEmi")
                        .HasColumnType("int");

                    b.Property<int>("Serie")
                        .HasColumnType("int");

                    b.Property<int?>("SessaoId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("SysDInsert")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SysDUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SysIdEnvio")
                        .HasColumnType("int");

                    b.Property<bool>("SysIsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("TpAmb")
                        .HasColumnType("int");

                    b.Property<int>("TpEmis")
                        .HasColumnType("int");

                    b.Property<int>("TpImp")
                        .HasColumnType("int");

                    b.Property<int>("TpNF")
                        .HasColumnType("int");

                    b.Property<string>("VerProc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Versao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XJust")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tbMovDados", (string)null);
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Identificacao.NFref", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AAMM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CUF")
                        .HasColumnType("int");

                    b.Property<string>("IE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdeId")
                        .HasColumnType("int");

                    b.Property<int?>("IdeId1")
                        .HasColumnType("int");

                    b.Property<string>("Mod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NCOO")
                        .HasColumnType("int");

                    b.Property<int>("NECF")
                        .HasColumnType("int");

                    b.Property<int>("NNF")
                        .HasColumnType("int");

                    b.Property<string>("RefNFe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Serie")
                        .HasColumnType("int");

                    b.Property<DateTime>("SysDInsert")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SysDUpdate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SysIsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IdeId");

                    b.HasIndex("IdeId1");

                    b.ToTable("tbMovNFRefs", (string)null);
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Intermediador.InfIntermed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdCadIntTran")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SysDInsert")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SysDUpdate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SysIsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IdeId");

                    b.ToTable("tbMovInfIntermed", (string)null);
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Pagamento.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CAut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CNSU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DetPagId")
                        .HasColumnType("int");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NroCartao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SysDInsert")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SysDUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SysIdEnvio")
                        .HasColumnType("int");

                    b.Property<bool>("SysIsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("TBand")
                        .HasColumnType("int");

                    b.Property<int?>("TpIntegra")
                        .HasColumnType("int");

                    b.Property<string>("ViaConsumidor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ViaEstabelecimento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DetPagId")
                        .IsUnique();

                    b.ToTable("tbMovPagDetCards", (string)null);
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Pagamento.DetPag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Cancelado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DVenc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdeId")
                        .HasColumnType("int");

                    b.Property<int?>("IndPag")
                        .HasColumnType("int");

                    b.Property<int>("PagamentoId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("SysDInsert")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SysDUpdate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SysIsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("TPag")
                        .HasColumnType("int");

                    b.Property<int>("TpSolicitado")
                        .HasColumnType("int");

                    b.Property<int>("TpTransacao")
                        .HasColumnType("int");

                    b.Property<decimal?>("VDesc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VOutro")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VPag")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VTroco")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdeId");

                    b.ToTable("tbMovPagDets", (string)null);
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.RespTecnico.InfRespTec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HashCSRT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdCSRT")
                        .HasColumnType("int");

                    b.Property<int>("IdeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SysDInsert")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SysDUpdate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SysIsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("XContato")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdeId");

                    b.ToTable("tbMovInfRespTecs", (string)null);
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Retirada.RetiradaDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContratoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DFinal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DInicial")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<string>("Mod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QArquivos")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("SysDInsert")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SysDUpdate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SysIsDeleted")
                        .HasColumnType("bit");

                    b.Property<long?>("Tamanho")
                        .HasColumnType("bigint");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tbRetiradaDocumentos", (string)null);
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Total.ICMSTot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SysDInsert")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SysDUpdate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SysIsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("VBC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VBCST")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VCOFINS")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VDesc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VFCP")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VFCPST")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VFCPSTRet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VFCPUFDest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VFrete")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VICMS")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VICMSDeson")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VICMSUFDest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VICMSUFRemet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VII")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VIPI")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VIPIDevol")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VNF")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VOutro")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VPIS")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VProd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VST")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VSeg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VTotTrib")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdeId");

                    b.ToTable("tbMovICMSTotais", (string)null);
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Total.ISSQNtot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CRegTrib")
                        .HasColumnType("int");

                    b.Property<string>("DCompet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SysDInsert")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SysDUpdate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SysIsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal?>("VBC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VCOFINS")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VDeducao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VDescCond")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VDescIncond")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VISS")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VISSRet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VOutro")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VPIS")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VServ")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdeId");

                    b.ToTable("tbMovISSQNTotais", (string)null);
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Total.RetTrib", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SysDInsert")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SysDUpdate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SysIsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal?>("VBCIRRF")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VBCRetPrev")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VIRRF")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VRetCOFINS")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VRetCSLL")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VRetPIS")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VRetPrev")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdeId");

                    b.ToTable("tbMovRetTribs", (string)null);
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Transporte.Lacre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NLacre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SysDInsert")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SysDUpdate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SysIsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("VolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VolId");

                    b.ToTable("tbMovTranspVolLacres", (string)null);
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Transporte.Reboque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Balsa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RNTC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SysDInsert")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SysDUpdate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SysIsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("TranspId")
                        .HasColumnType("int");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vagao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TranspId");

                    b.ToTable("tbMovTranspReboques", (string)null);
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Transporte.RetTransp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CFOP")
                        .HasColumnType("int");

                    b.Property<long>("CMunFG")
                        .HasColumnType("bigint");

                    b.Property<decimal>("PICMSRet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("SysDInsert")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SysDUpdate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SysIsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("TranspId")
                        .HasColumnType("int");

                    b.Property<decimal>("VBCRet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VICMSRet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VServ")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TranspId");

                    b.ToTable("tbMovTranspRets", (string)null);
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Transporte.Transp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdeId")
                        .HasColumnType("int");

                    b.Property<int>("ModFrete")
                        .HasColumnType("int");

                    b.Property<DateTime>("SysDInsert")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SysDUpdate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SysIsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IdeId");

                    b.ToTable("tbMovTransps", (string)null);
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Transporte.Transporta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CadastroId")
                        .HasColumnType("int");

                    b.Property<string>("Doc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SysDInsert")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SysDUpdate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SysIsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("TranspId")
                        .HasColumnType("int");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XEnder")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XMun")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TranspId");

                    b.ToTable("tbMovTransportas", (string)null);
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Transporte.VeicTransp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RNTC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SysDInsert")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SysDUpdate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SysIsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("TranspId")
                        .HasColumnType("int");

                    b.Property<int>("TransportaId")
                        .HasColumnType("int");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TransportaId");

                    b.ToTable("tbMovTranspVeics", (string)null);
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Transporte.Vol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Esp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NVol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PesoB")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PesoL")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("QVol")
                        .HasColumnType("int");

                    b.Property<DateTime>("SysDInsert")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SysDUpdate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SysIsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("TranspId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TranspId");

                    b.ToTable("tbMovTranspVols", (string)null);
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Cobranca.Dup", b =>
                {
                    b.HasOne("ISync.Entidades.Movimentacao.Pagamento.DetPag", "DetPag")
                        .WithMany()
                        .HasForeignKey("DetPagId");

                    b.HasOne("ISync.Entidades.Movimentacao.Cobranca.Fat", "Fat")
                        .WithMany("Dups")
                        .HasForeignKey("FatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DetPag");

                    b.Navigation("Fat");
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Cobranca.Fat", b =>
                {
                    b.HasOne("ISync.Entidades.Movimentacao.Identificacao.Ide", "Ide")
                        .WithMany("Fats")
                        .HasForeignKey("IdeId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ide");
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Cobranca.FatPagProd", b =>
                {
                    b.HasOne("ISync.Entidades.Movimentacao.Cobranca.Fat", null)
                        .WithMany("PagProds")
                        .HasForeignKey("FatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Destinatario.Dest", b =>
                {
                    b.HasOne("ISync.Entidades.Movimentacao.Identificacao.Ide", "Ide")
                        .WithMany("Dest")
                        .HasForeignKey("IdeId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ide");
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Detalhe.DeclaracaoImportacao.Adi", b =>
                {
                    b.HasOne("ISync.Entidades.Movimentacao.Detalhe.DeclaracaoImportacao.DI", "DI")
                        .WithMany("Adis")
                        .HasForeignKey("DIId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DI");
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Detalhe.DeclaracaoImportacao.DI", b =>
                {
                    b.HasOne("ISync.Entidades.Movimentacao.Detalhe.Prod", "Prod")
                        .WithMany()
                        .HasForeignKey("ProdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prod");
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Detalhe.Exportacao.DetExport", b =>
                {
                    b.HasOne("ISync.Entidades.Movimentacao.Detalhe.Prod", "Prod")
                        .WithMany("DetExports")
                        .HasForeignKey("ProdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prod");
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Detalhe.Exportacao.ExportInd", b =>
                {
                    b.HasOne("ISync.Entidades.Movimentacao.Detalhe.Exportacao.DetExport", "DetExport")
                        .WithMany("ExportInds")
                        .HasForeignKey("DetExportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DetExport");
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Detalhe.Prod", b =>
                {
                    b.HasOne("ISync.Entidades.Movimentacao.Identificacao.Ide", "Ide")
                        .WithMany("Prods")
                        .HasForeignKey("IdeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ide");
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Detalhe.ProdEspecifico.Comb", b =>
                {
                    b.HasOne("ISync.Entidades.Movimentacao.Detalhe.Prod", "Prod")
                        .WithMany("Combs")
                        .HasForeignKey("ProdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ISync.Entidades.Movimentacao.Detalhe.ProdEspecifico.OrigComb", "OrigComb", b1 =>
                        {
                            b1.Property<int>("CombId")
                                .HasColumnType("int");

                            b1.Property<int?>("cUFOrig")
                                .HasColumnType("int")
                                .HasColumnName("OrigComb_CUFOrig");

                            b1.Property<int>("indImport")
                                .HasColumnType("int")
                                .HasColumnName("OrigComb_IndImport");

                            b1.Property<decimal>("pOrig")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("OrigComb_POrig");

                            b1.HasKey("CombId");

                            b1.ToTable("MovProdCombOrigCombs");

                            b1.WithOwner()
                                .HasForeignKey("CombId");
                        });

                    b.Navigation("OrigComb")
                        .IsRequired();

                    b.Navigation("Prod");
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Detalhe.ProdEspecifico.Encerrante", b =>
                {
                    b.HasOne("ISync.Entidades.Movimentacao.Detalhe.ProdEspecifico.Comb", "Comb")
                        .WithMany("Encerrantes")
                        .HasForeignKey("CombId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comb");
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Detalhe.Tributacao.Estadual.ICMS", b =>
                {
                    b.HasOne("ISync.Entidades.Movimentacao.Detalhe.Prod", "Prod")
                        .WithMany("ICMS")
                        .HasForeignKey("ProdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prod");
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Detalhe.Tributacao.Federal.COFINS", b =>
                {
                    b.HasOne("ISync.Entidades.Movimentacao.Detalhe.Prod", "Prod")
                        .WithMany("COFINS")
                        .HasForeignKey("ProdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prod");
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Detalhe.Tributacao.Federal.II", b =>
                {
                    b.HasOne("ISync.Entidades.Movimentacao.Detalhe.Prod", "Prod")
                        .WithMany("II")
                        .HasForeignKey("ProdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prod");
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Detalhe.Tributacao.Federal.IPI", b =>
                {
                    b.HasOne("ISync.Entidades.Movimentacao.Detalhe.Prod", "Prod")
                        .WithMany("IPI")
                        .HasForeignKey("ProdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prod");
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Detalhe.Tributacao.Federal.PIS", b =>
                {
                    b.HasOne("ISync.Entidades.Movimentacao.Detalhe.Prod", "Prod")
                        .WithMany("PIS")
                        .HasForeignKey("ProdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prod");
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Detalhe.Tributacao.Municipal.ISSQN", b =>
                {
                    b.HasOne("ISync.Entidades.Movimentacao.Detalhe.Prod", "Prod")
                        .WithMany("ISSQN")
                        .HasForeignKey("ProdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prod");
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Emitente.Emit", b =>
                {
                    b.HasOne("ISync.Entidades.Movimentacao.Identificacao.Ide", "Ide")
                        .WithMany("Emit")
                        .HasForeignKey("IdeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ide");
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Identificacao.NFref", b =>
                {
                    b.HasOne("ISync.Entidades.Movimentacao.Identificacao.Ide", "Ide")
                        .WithMany("NFref")
                        .HasForeignKey("IdeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ISync.Entidades.Movimentacao.Identificacao.Ide", null)
                        .WithMany("NFrefs")
                        .HasForeignKey("IdeId1");

                    b.Navigation("Ide");
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Intermediador.InfIntermed", b =>
                {
                    b.HasOne("ISync.Entidades.Movimentacao.Identificacao.Ide", "Ide")
                        .WithMany("InfIntermed")
                        .HasForeignKey("IdeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ide");
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Pagamento.Card", b =>
                {
                    b.HasOne("ISync.Entidades.Movimentacao.Pagamento.DetPag", "DetPag")
                        .WithOne("Card")
                        .HasForeignKey("ISync.Entidades.Movimentacao.Pagamento.Card", "DetPagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DetPag");
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Pagamento.DetPag", b =>
                {
                    b.HasOne("ISync.Entidades.Movimentacao.Identificacao.Ide", "Ide")
                        .WithMany("Pags")
                        .HasForeignKey("IdeId");

                    b.Navigation("Ide");
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.RespTecnico.InfRespTec", b =>
                {
                    b.HasOne("ISync.Entidades.Movimentacao.Identificacao.Ide", "Ide")
                        .WithMany("InfRespTec")
                        .HasForeignKey("IdeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ide");
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Total.ICMSTot", b =>
                {
                    b.HasOne("ISync.Entidades.Movimentacao.Identificacao.Ide", "Ide")
                        .WithMany("ICMSTot")
                        .HasForeignKey("IdeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ide");
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Total.ISSQNtot", b =>
                {
                    b.HasOne("ISync.Entidades.Movimentacao.Identificacao.Ide", "Ide")
                        .WithMany("ISSQNtot")
                        .HasForeignKey("IdeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ide");
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Total.RetTrib", b =>
                {
                    b.HasOne("ISync.Entidades.Movimentacao.Identificacao.Ide", "Ide")
                        .WithMany("RetTrib")
                        .HasForeignKey("IdeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ide");
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Transporte.Lacre", b =>
                {
                    b.HasOne("ISync.Entidades.Movimentacao.Transporte.Vol", "Vol")
                        .WithMany("Lacres")
                        .HasForeignKey("VolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vol");
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Transporte.Reboque", b =>
                {
                    b.HasOne("ISync.Entidades.Movimentacao.Transporte.Transp", "Transp")
                        .WithMany("Reboques")
                        .HasForeignKey("TranspId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transp");
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Transporte.RetTransp", b =>
                {
                    b.HasOne("ISync.Entidades.Movimentacao.Transporte.Transp", "Transp")
                        .WithMany("RetTransps")
                        .HasForeignKey("TranspId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transp");
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Transporte.Transp", b =>
                {
                    b.HasOne("ISync.Entidades.Movimentacao.Identificacao.Ide", "Ide")
                        .WithMany("Transps")
                        .HasForeignKey("IdeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ide");
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Transporte.Transporta", b =>
                {
                    b.HasOne("ISync.Entidades.Movimentacao.Transporte.Transp", "Transp")
                        .WithMany("Transportas")
                        .HasForeignKey("TranspId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transp");
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Transporte.VeicTransp", b =>
                {
                    b.HasOne("ISync.Entidades.Movimentacao.Transporte.Transporta", "Transporta")
                        .WithMany()
                        .HasForeignKey("TransportaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transporta");
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Transporte.Vol", b =>
                {
                    b.HasOne("ISync.Entidades.Movimentacao.Transporte.Transp", "Transp")
                        .WithMany("Vols")
                        .HasForeignKey("TranspId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transp");
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Cobranca.Fat", b =>
                {
                    b.Navigation("Dups");

                    b.Navigation("PagProds");
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Detalhe.DeclaracaoImportacao.DI", b =>
                {
                    b.Navigation("Adis");
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Detalhe.Exportacao.DetExport", b =>
                {
                    b.Navigation("ExportInds");
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Detalhe.Prod", b =>
                {
                    b.Navigation("COFINS");

                    b.Navigation("Combs");

                    b.Navigation("DetExports");

                    b.Navigation("ICMS");

                    b.Navigation("II");

                    b.Navigation("IPI");

                    b.Navigation("ISSQN");

                    b.Navigation("PIS");
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Detalhe.ProdEspecifico.Comb", b =>
                {
                    b.Navigation("Encerrantes");
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Identificacao.Ide", b =>
                {
                    b.Navigation("Dest");

                    b.Navigation("Emit");

                    b.Navigation("Fats");

                    b.Navigation("ICMSTot");

                    b.Navigation("ISSQNtot");

                    b.Navigation("InfIntermed");

                    b.Navigation("InfRespTec");

                    b.Navigation("NFref");

                    b.Navigation("NFrefs");

                    b.Navigation("Pags");

                    b.Navigation("Prods");

                    b.Navigation("RetTrib");

                    b.Navigation("Transps");
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Pagamento.DetPag", b =>
                {
                    b.Navigation("Card")
                        .IsRequired();
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Transporte.Transp", b =>
                {
                    b.Navigation("Reboques");

                    b.Navigation("RetTransps");

                    b.Navigation("Transportas");

                    b.Navigation("Vols");
                });

            modelBuilder.Entity("ISync.Entidades.Movimentacao.Transporte.Vol", b =>
                {
                    b.Navigation("Lacres");
                });
#pragma warning restore 612, 618
        }
    }
}
