using System.ComponentModel;

namespace ISync.Core.Enums
{
    public enum EnumTpEmpresaConfigs
    {
        [ValorPadrao("15")]
        [VMinPadrao(1)]
        [VMaxPadrao(10000)]
        [TpControle(0)]
        [TpTxt("Numero")]
        [ItemDrop("")]
        [Ordem(9)]
        [Grupo("01-Configurações do Sistema")]
        [Description("Número Registros por Página")]
        Config100 = 100,

        [ValorPadrao("2")]
        [VMinPadrao(0)]
        [VMaxPadrao(10)]
        [TpControle(1)]
        [TpTxt("Numero")]
        [ItemDrop("")]
        [Ordem(10)]
        [Grupo("01-Configurações do Sistema")]
        [Description("Casas Decimais para Valores")]
        Config101 = 101,

        [ValorPadrao("3")]
        [VMinPadrao(0)]
        [VMaxPadrao(4)]
        [TpControle(1)]
        [TpTxt("Numero")]
        [ItemDrop("")]
        [Ordem(11)]
        [Grupo("01-Configurações do Sistema")]
        [Description("Casas Decimais para Quantidade")]
        Config102 = 102,

        [ValorPadrao("3")]
        [VMinPadrao(2)]
        [VMaxPadrao(5)]
        [TpControle(1)]
        [TpTxt("Texto")]
        [ItemDrop("(UTC-2)Horário de verão|(UTC-3)Brasília|(UTC-4)Amazonia|(UTC-5)Acre")]
        [Ordem(8)]
        [Grupo("01-Configurações do Sistema")]
        [Description("Fuso Horário")]
        Config104 = 104,

        [ValorPadrao("1")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Texto")]
        [ItemDrop("")]
        [Ordem(2)]
        [Grupo("01-Configurações do Sistema")]
        [Description("Id do Plano Padrão")]
        Config107 = 107,

        [ValorPadrao("1")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Texto")]
        [ItemDrop("")]
        [Ordem(3)]
        [Grupo("01-Configurações do Sistema")]
        [Description("Id Forma de Pgto Padrão")]
        Config108 = 108,

        [ValorPadrao("1")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Texto")]
        [ItemDrop("")]
        [Ordem(7)]
        [Grupo("01-Configurações do Sistema")]
        [Description("Id Transportadora Padrão")]
        Config111 = 111,

        [ValorPadrao("")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Texto")]
        [ItemDrop("")]
        [Ordem(1)]
        [Grupo("01-Configurações do Sistema")]
        [Description("Url do Certificado Digital")]
        Config119 = 119,

        [ValorPadrao("xxx")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Texto")]
        [ItemDrop("")]
        [Ordem(1)]
        [Grupo("01-Configurações do Sistema")]
        [Description("Numero de Série do Certificado Digital")]
        Config120 = 120,

        [ValorPadrao("1")]
        [VMinPadrao(0)]
        [VMaxPadrao(1)]
        [TpControle(1)]
        [TpTxt("Numero")]
        [ItemDrop("Em qualquer parte|Exatamente")]
        [Ordem(16)]
        [Grupo("01-Configurações do Sistema")]
        [Description("Tipo de Procura por Código")]
        Config122 = 122,

        [ValorPadrao("999999")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Numero")]
        [ItemDrop("")]
        [Ordem(5)]
        [Grupo("01-Configurações do Sistema")]
        [Description("Valor Máximo (Item ou Pagamento)")]
        Config124 = 124,

        [ValorPadrao("9999")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Numero")]
        [ItemDrop("")]
        [Ordem(5)]
        [Grupo("01-Configurações do Sistema")]
        [Description("Quantidade Máxima Permitida")]
        Config125 = 125,

        [ValorPadrao("1")]
        [VMinPadrao(0)]
        [VMaxPadrao(1)]
        [TpControle(1)]
        [TpTxt("Numero")]
        [ItemDrop("Não|Sim")]
        [Ordem(17)]
        [Grupo("01-Configurações do Sistema")]
        [Description("Pesquisar Produto Também pelo ID")]
        Config128 = 128,

        [ValorPadrao("1")]
        [VMinPadrao(0)]
        [VMaxPadrao(1)]
        [TpControle(1)]
        [TpTxt("Numero")]
        [ItemDrop("Nunca Vincular|Sempre Vincular")]
        [Ordem(6)]
        [Grupo("81-Cartão Fidelidade")]
        [Description("Vincular Parceiro na Venda")]
        Config130 = 130,

        [ValorPadrao("Valor Aproximado dos Tributos: R$ [vTotTrib] ([pTotTrib]%) - Fonte IBPT")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Texto")]
        [ItemDrop("")]
        [Ordem(5)]
        [Grupo("01-Configurações do Sistema")]
        [Description("Informação Complementar")]
        Config149 = 149,

        [ValorPadrao("")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Numero")]
        [ItemDrop("")]
        [Ordem(1)]
        [Grupo("02-Responsável Técnico (NFe)")]
        [Description("CNPJ")]
        Config180 = 180,

        [ValorPadrao("")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Texto")]
        [ItemDrop("")]
        [Ordem(3)]
        [Grupo("02-Responsável Técnico (NFe)")]
        [Description("Contato")]
        Config181 = 181,

        [ValorPadrao("")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Texto")]
        [ItemDrop("")]
        [Ordem(4)]
        [Grupo("02-Responsável Técnico (NFe)")]
        [Description("E-mail")]
        Config182 = 182,

        [ValorPadrao("")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Numero")]
        [ItemDrop("")]
        [Ordem(2)]
        [Grupo("02-Responsável Técnico (NFe)")]
        [Description("Telefone")]
        Config183 = 183,

        [ValorPadrao("")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Texto")]
        [ItemDrop("")]
        [Ordem(5)]
        [Grupo("02-Responsável Técnico (NFe)")]
        [Description("Id do Código")]
        Config184 = 184,

        [ValorPadrao("")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Texto")]
        [ItemDrop("")]
        [Ordem(6)]
        [Grupo("02-Responsável Técnico (NFe)")]
        [Description("Código de Segurança")]
        Config185 = 185,

        [ValorPadrao("1")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Texto")]
        [ItemDrop("")]
        [Ordem(7)]
        [Grupo("01-Configurações do Sistema")]
        [Description("Id do Cliente Padrão")]
        Config326 = 326,

        [ValorPadrao("1")]
        [VMinPadrao(0)]
        [VMaxPadrao(1)]
        [TpControle(1)]
        [TpTxt("Numero")]
        [ItemDrop("Informa Forma de Pagamento/Parcela|Informa Número da Nota/Parcela")]
        [Ordem(17)]
        [Grupo("21-Configurações NFCe")]
        [Description("Modelo de Geração de Duplicatas em Documentos Fiscais")]
        Config506 = 506,

        [ValorPadrao("https://homologacao.nfce.fazenda.sp.gov.br/ws/nfeautorizacao.asmx")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Texto")]
        [ItemDrop("")]
        [Ordem(0)]
        [Grupo("21-Configurações NFCe")]
        [Description("WebService Autorização")]
        Config510 = 510,

        [ValorPadrao("https://homologacao.nfce.fazenda.sp.gov.br/ws/nferetautorizacao.asmx")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Texto")]
        [ItemDrop("")]
        [Ordem(0)]
        [Grupo("21-Configurações NFCe")]
        [Description("WebService RetAutorização")]
        Config511 = 511,

        [ValorPadrao("https://homologacao.nfce.fazenda.sp.gov.br/ws/recepcaoevento.asmx")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Texto")]
        [ItemDrop("")]
        [Ordem(0)]
        [Grupo("21-Configurações NFCe")]
        [Description("WebService RecepçãoEvento")]
        Config512 = 512,

        [ValorPadrao("https://homologacao.nfce.fazenda.sp.gov.br/ws/nfeinutilizacao2.asmx")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Texto")]
        [ItemDrop("")]
        [Ordem(0)]
        [Grupo("21-Configurações NFCe")]
        [Description("WebService Inutilização")]
        Config513 = 513,

        [ValorPadrao("https://homologacao.nfce.fazenda.sp.gov.br/ws/nfeconsulta2.asmx")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Texto")]
        [ItemDrop("")]
        [Ordem(0)]
        [Grupo("21-Configurações NFCe")]
        [Description("WebService ConsultaProtocolo")]
        Config514 = 514,

        [ValorPadrao("https://homologacao.nfce.fazenda.sp.gov.br/ws/nfestatusservico2.asmx")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Texto")]
        [ItemDrop("")]
        [Ordem(0)]
        [Grupo("21-Configurações NFCe")]
        [Description("WebService StatusServico")]
        Config515 = 515,

        [ValorPadrao("https://www.nfce.fazenda.sp.gov.br/consulta")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Texto")]
        [ItemDrop("")]
        [Ordem(0)]
        [Grupo("21-Configurações NFCe")]
        [Description("Url Endereço de Consulta QR Code")]
        Config516 = 516,

        [ValorPadrao("https://www.nfce.fazenda.sp.gov.br/consulta")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Texto")]
        [ItemDrop("")]
        [Ordem(0)]
        [Grupo("21-Configurações NFCe")]
        [Description("Url Endereço de Consulta - DANFE")]
        Config517 = 517,

        [ValorPadrao("000001")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Numero")]
        [ItemDrop("")]
        [Ordem(1)]
        [Grupo("21-Configurações NFCe")]
        [Description("Id do CSC")]
        Config518 = 518,

        [ValorPadrao("")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Texto")]
        [ItemDrop("")]
        [Ordem(1)]
        [Grupo("21-Configurações NFCe")]
        [Description("Código de Segurança do Contribuinte (CSC)")]
        Config519 = 519,

        [ValorPadrao("9")]
        [VMinPadrao(0)]
        [VMaxPadrao(9)]
        [TpControle(1)]
        [TpTxt("Numero")]
        [ItemDrop("Contratação do Frete por conta do Remetente (CIF)|Contratação do Frete por conta do Destinatário (FOB)|Contratação do Frete por conta de Terceiros|Transporte Próprio por conta ")]
        [Ordem(0)]
        [Grupo("21-Configurações NFCe")]
        [Description("Modalidade de Frete Padrão")]
        Config520 = 520,

        [ValorPadrao("5")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Numero")]
        [ItemDrop("")]
        [Ordem(3)]
        [Grupo("21-Configurações NFCe")]
        [Description("Tempo mínimo da Contingência (Minutos)")]
        Config530 = 530,

        [ValorPadrao("2")]
        [VMinPadrao(0)]
        [VMaxPadrao(2)]
        [TpControle(1)]
        [TpTxt("Numero")]
        [ItemDrop("Somente por problemas técnicos|Sempre em Contingência|Não Permitir Contingência")]
        [Ordem(2)]
        [Grupo("21-Configurações NFCe")]
        [Description("Modelo de Contingência")]
        Config531 = 531,

        [ValorPadrao("4.00")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Texto")]
        [ItemDrop("")]
        [Ordem(0)]
        [Grupo("21-Configurações NFCe")]
        [Description("Versão do Layout")]
        Config545 = 545,

        [ValorPadrao("")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Texto")]
        [ItemDrop("")]
        [Ordem(12)]
        [Grupo("20-Configurações SAT")]
        [Description("CNPJ da Software House")]
        Config610 = 610,

        [ValorPadrao("")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Texto")]
        [ItemDrop("")]
        [Ordem(12)]
        [Grupo("20-Configurações SAT")]
        [Description("Assinatura do Aplicativo Comercial")]
        Config611 = 611,

        [ValorPadrao("")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Texto")]
        [ItemDrop("")]
        [Ordem(12)]
        [Grupo("20-Configurações SAT")]
        [Description("Código de Ativação do Aparelho")]
        Config612 = 612,

        [ValorPadrao("")]
        [VMinPadrao(0)]
        [VMaxPadrao(9)]
        [TpControle(1)]
        [TpTxt("Numero")]
        [ItemDrop("Contratação do Frete por conta do Remetente (CIF)|Contratação do Frete por conta do Destinatário (FOB)|Contratação do Frete por conta de Terceiros|Transporte Próprio por conta ")]
        [Ordem(5)]
        [Grupo("20-Configurações SAT")]
        [Description("Modalidade de Frete Padrão")]
        Config620 = 620,

        [ValorPadrao("")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Texto")]
        [ItemDrop("")]
        [Ordem(12)]
        [Grupo("20-Configurações SAT")]
        [Description("Versão do Layout")]
        Config645 = 645,

        [ValorPadrao("")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Texto")]
        [ItemDrop("Automatico|cdecl|stdcall")]
        [Ordem(13)]
        [Grupo("20-Configurações SAT")]
        [Description("Modelo DLL")]
        Config646 = 646,

        [ValorPadrao("0")]
        [VMinPadrao(0)]
        [VMaxPadrao(1)]
        [TpControle(1)]
        [TpTxt("Numero")]
        [ItemDrop("Não|Sim")]
        [Ordem(31)]
        [Grupo("01-Configurações do Sistema")]
        [Description("Validar Código EAN")]
        Config723 = 723,

        [ValorPadrao("1")]
        [VMinPadrao(0)]
        [VMaxPadrao(1)]
        [TpControle(1)]
        [TpTxt("Numero")]
        [ItemDrop("Não|Sim")]
        [Ordem(30)]
        [Grupo("01-Configurações do Sistema")]
        [Description("Permitir Produto Sem Código")]
        Config724 = 724,

        [ValorPadrao("0")]
        [VMinPadrao(0)]
        [VMaxPadrao(1)]
        [TpControle(1)]
        [TpTxt("Numero")]
        [ItemDrop("Não|Sim")]
        [Ordem(29)]
        [Grupo("01-Configurações do Sistema")]
        [Description("Aceitar Apenas Número nos Códigos")]
        Config725 = 725,

        [ValorPadrao("10")]
        [VMinPadrao(0)]
        [VMaxPadrao(100)]
        [TpControle(0)]
        [TpTxt("Numero")]
        [ItemDrop("")]
        [Ordem(5)]
        [Grupo("41-Servidor de Terminal de Vendas")]
        [Description("Percentual de Garçon")]
        Config800 = 800,

        [ValorPadrao("0")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Numero")]
        [ItemDrop("")]
        [Ordem(6)]
        [Grupo("41-Servidor de Terminal de Vendas")]
        [Description("Valor de Couvert")]
        Config801 = 801,

        [ValorPadrao("1|1")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Texto")]
        [ItemDrop("")]
        [Ordem(2)]
        [Grupo("41-Servidor de Terminal de Vendas")]
        [Description("Mesa Inicial|Comanda Inicial")]
        Config802 = 802,

        [ValorPadrao("50|100")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Texto")]
        [ItemDrop("")]
        [Ordem(3)]
        [Grupo("41-Servidor de Terminal de Vendas")]
        [Description("Mesa Final|Comanda Final")]
        Config803 = 803,

        [ValorPadrao("C")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Texto")]
        [ItemDrop("")]
        [Ordem(4)]
        [Grupo("41-Servidor de Terminal de Vendas")]
        [Description("Prefixo de Comanda")]
        Config804 = 804,

        [ValorPadrao("3")]
        [VMinPadrao(0)]
        [VMaxPadrao(4)]
        [TpControle(1)]
        [TpTxt("Numero")]
        [ItemDrop("Desabilitado|Impressão por Item|Impressão por Pedido|Impressão por Item Detalhado|Impressão por Pedido Detalhado")]
        [Ordem(1)]
        [Grupo("41-Servidor de Terminal de Vendas")]
        [Description("Tipo de Impressão de Setor")]
        Config805 = 805,

        [ValorPadrao("")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Texto")]
        [ItemDrop("")]
        [Ordem(7)]
        [Grupo("41-Servidor de Terminal de Vendas")]
        [Description("Cabeçalho de Impressão")]
        Config806 = 806,

        [ValorPadrao("")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Texto")]
        [ItemDrop("")]
        [Ordem(8)]
        [Grupo("41-Servidor de Terminal de Vendas")]
        [Description("Rodapé de Impressão")]
        Config807 = 807,

        [ValorPadrao("C:\\Saurus\\Saurus PDV\\Backup\\Terminal Server")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Texto")]
        [ItemDrop("")]
        [Ordem(9)]
        [Grupo("41-Servidor de Terminal de Vendas")]
        [Description("Local de Backup das Vendas")]
        Config808 = 808,

        [ValorPadrao("")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Texto")]
        [ItemDrop("")]
        [Ordem(10)]
        [Grupo("41-Servidor de Terminal de Vendas")]
        [Description("Cabeçalho de Impressão Setor")]
        Config809 = 809,

        [ValorPadrao("")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Texto")]
        [ItemDrop("")]
        [Ordem(11)]
        [Grupo("41-Servidor de Terminal de Vendas")]
        [Description("Rodapé de Impressão Setor")]
        Config810 = 810,

        [ValorPadrao("0")]
        [VMinPadrao(0)]
        [VMaxPadrao(15)]
        [TpControle(1)]
        [TpTxt("Numero")]
        [ItemDrop("")]
        [Ordem(15)]
        [Grupo("41-Servidor de Terminal de Vendas")]
        [Description("Minutos para Confirmação Automática de Itens")]
        Config811 = 811,

        [ValorPadrao("5")]
        [VMinPadrao(0)]
        [VMaxPadrao(120)]
        [TpControle(1)]
        [TpTxt("Numero")]
        [ItemDrop("")]
        [Ordem(15)]
        [Grupo("41-Servidor de Terminal de Vendas")]
        [Description("Minutos para Alerta de Cliente Inativo")]
        Config812 = 812,

        [ValorPadrao("0")]
        [VMinPadrao(0)]
        [VMaxPadrao(1)]
        [TpControle(1)]
        [TpTxt("Numero")]
        [ItemDrop("Mostrar em Ambas as Telas|Separar Comandas para Atalho Z e Avulsos para Atalho K")]
        [Ordem(15)]
        [Grupo("41-Servidor de Terminal de Vendas")]
        [Description("Separar Comandas e Pedidos Avulsos (Z e K)")]
        Config813 = 813,

        [ValorPadrao("0")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Numero")]
        [ItemDrop("")]
        [Ordem(16)]
        [Grupo("41-Servidor de Terminal de Vendas")]
        [Description("Id Garçon para Vinculação de Taxa de Serviço")]
        Config814 = 814,

        [ValorPadrao("2")]
        [VMinPadrao(0)]
        [VMaxPadrao(2)]
        [TpControle(1)]
        [TpTxt("Numero")]
        [ItemDrop("Não Apitar|Por Pedido|Por Item")]
        [Ordem(17)]
        [Grupo("41-Servidor de Terminal de Vendas")]
        [Description("Beep para Impressora Setor")]
        Config815 = 815,

        [ValorPadrao("")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Texto")]
        [ItemDrop("")]
        [Ordem(18)]
        [Grupo("41-Servidor de Terminal de Vendas")]
        [Description("Caminho de Comunicação para Catracas Advances")]
        Config816 = 816,

        [ValorPadrao("1")]
        [VMinPadrao(0)]
        [VMaxPadrao(1)]
        [TpControle(1)]
        [TpTxt("Numero")]
        [ItemDrop("Não agrupar|Agrupar")]
        [Ordem(18)]
        [Grupo("41-Servidor de Terminal de Vendas")]
        [Description("Agrupar Itens")]
        Config820 = 820,

        [ValorPadrao("3")]
        [VMinPadrao(0)]
        [VMaxPadrao(365)]
        [TpControle(0)]
        [TpTxt("Numero")]
        [ItemDrop("")]
        [Ordem(19)]
        [Grupo("41-Servidor de Terminal de Vendas")]
        [Description("Dias de backup dos Pedidos")]
        Config821 = 821,

        [ValorPadrao("0")]
        [VMinPadrao(0)]
        [VMaxPadrao(1)]
        [TpControle(1)]
        [TpTxt("Texto")]
        [ItemDrop("Não|Sim")]
        [Ordem(20)]
        [Grupo("41-Servidor de Terminal de Vendas")]
        [Description("Deletar Pedidos Vazios (Tempo: Confirmação Automática)")]
        Config822 = 822,

        [ValorPadrao("1")]
        [VMinPadrao(0)]
        [VMaxPadrao(1)]
        [TpControle(1)]
        [TpTxt("Texto")]
        [ItemDrop("Não|Sim")]
        [Ordem(21)]
        [Grupo("41-Servidor de Terminal de Vendas")]
        [Description("Imprimir Código do Pedido")]
        Config823 = 823,

        [ValorPadrao("0")]
        [VMinPadrao(0)]
        [VMaxPadrao(3)]
        [TpControle(1)]
        [TpTxt("Texto")]
        [ItemDrop("Não imprimir|Imprimir setor|Imprimir conferência|Imprimir em ambos")]
        [Ordem(22)]
        [Grupo("41-Servidor de Terminal de Vendas")]
        [Description("Imprimir Cancelamento de Item")]
        Config824 = 824,

        [ValorPadrao("0")]
        [VMinPadrao(0)]
        [VMaxPadrao(1)]
        [TpControle(1)]
        [TpTxt("Texto")]
        [ItemDrop("Não|Sim")]
        [Ordem(24)]
        [Grupo("41-Servidor de Terminal de Vendas")]
        [Description("Bloquear Mesa/Comanda ao Imprimir Fechamento")]
        Config825 = 825,

        [ValorPadrao("")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Texto")]
        [ItemDrop("")]
        [Ordem(23)]
        [Grupo("41-Servidor de Terminal de Vendas")]
        [Description("Caminho da Impressora de Conferência do Cancelamento")]
        Config826 = 826,

        [ValorPadrao("210")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Numero")]
        [ItemDrop("")]
        [Ordem(4)]
        [Grupo("40-Ponto de Venda")]
        [Description("Hue - Cor Primária")]
        Config900 = 900,

        [ValorPadrao("210")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Numero")]
        [ItemDrop("")]
        [Ordem(5)]
        [Grupo("40-Ponto de Venda")]
        [Description("Hue - Cor Secundária")]
        Config901 = 901,

        [ValorPadrao("210")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Numero")]
        [ItemDrop("")]
        [Ordem(6)]
        [Grupo("40-Ponto de Venda")]
        [Description("Hue - Cor Terciária")]
        Config902 = 902,

        [ValorPadrao("0")]
        [VMinPadrao(-1)]
        [VMaxPadrao(-1)]
        [TpControle(-0)]
        [TpTxt("Texto")]
        [ItemDrop("")]
        [Ordem(7)]
        [Grupo("40-Ponto de Venda")]
        [Description("Saturação - Cor Primária")]
        Config903 = 903,

        [ValorPadrao("0")]
        [VMinPadrao(-1)]
        [VMaxPadrao(-1)]
        [TpControle(-0)]
        [TpTxt("Texto")]
        [ItemDrop("")]
        [Ordem(8)]
        [Grupo("40-Ponto de Venda")]
        [Description("Saturação - Cor Secundária")]
        Config904 = 904,

        [ValorPadrao("0")]
        [VMinPadrao(-1)]
        [VMaxPadrao(-1)]
        [TpControle(-0)]
        [TpTxt("Texto")]
        [ItemDrop("")]
        [Ordem(9)]
        [Grupo("40-Ponto de Venda")]
        [Description("Saturação - Cor Terciária")]
        Config905 = 905,

        [ValorPadrao("0")]
        [VMinPadrao(-1)]
        [VMaxPadrao(-1)]
        [TpControle(-0)]
        [TpTxt("Texto")]
        [ItemDrop("")]
        [Ordem(10)]
        [Grupo("40-Ponto de Venda")]
        [Description("Brilho - Cor Primária")]
        Config906 = 906,

        [ValorPadrao("0")]
        [VMinPadrao(-1)]
        [VMaxPadrao(-1)]
        [TpControle(-0)]
        [TpTxt("Texto")]
        [ItemDrop("")]
        [Ordem(11)]
        [Grupo("40-Ponto de Venda")]
        [Description("Brilho - Cor Secundária")]
        Config907 = 907,

        [ValorPadrao("0")]
        [VMinPadrao(-1)]
        [VMaxPadrao(-1)]
        [TpControle(-0)]
        [TpTxt("Texto")]
        [ItemDrop("")]
        [Ordem(12)]
        [Grupo("40-Ponto de Venda")]
        [Description("Brilho - Cor Terciária")]
        Config908 = 908,

        [ValorPadrao("0")]
        [VMinPadrao(0)]
        [VMaxPadrao(1)]
        [TpControle(1)]
        [TpTxt("Numero")]
        [ItemDrop("Não|Sim")]
        [Ordem(3)]
        [Grupo("40-Ponto de Venda")]
        [Description("Utilizar Transportadora")]
        Config909 = 909,

        [ValorPadrao("1")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Numero")]
        [ItemDrop("")]
        [Ordem(16)]
        [Grupo("40-Ponto de Venda")]
        [Description("Cod Produto Genérico")]
        Config910 = 910,

        [ValorPadrao("0")]
        [VMinPadrao(0)]
        [VMaxPadrao(1)]
        [TpControle(1)]
        [TpTxt("Numero")]
        [ItemDrop("Não|Sim")]
        [Ordem(15)]
        [Grupo("40-Ponto de Venda")]
        [Description("Utilizar Edição Produto Genérico")]
        Config911 = 911,

        [ValorPadrao("0")]
        [VMinPadrao(0)]
        [VMaxPadrao(60)]
        [TpControle(1)]
        [TpTxt("Numero")]
        [ItemDrop("")]
        [Ordem(17)]
        [Grupo("40-Ponto de Venda")]
        [Description("Dias de Backup de Vendas Locais")]
        Config912 = 912,

        [ValorPadrao("0")]
        [VMinPadrao(0)]
        [VMaxPadrao(1)]
        [TpControle(1)]
        [TpTxt("Numero")]
        [ItemDrop("Não|Sim")]
        [Ordem(0)]
        [Grupo("40-Ponto de Venda")]
        [Description("Informações Adicionais em Movimentação de Valores")]
        Config913 = 913,

        [ValorPadrao("0")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Numero")]
        [ItemDrop("")]
        [Ordem(19)]
        [Grupo("40-Ponto de Venda")]
        [Description("Tempo Máximo de Sessão (Horas)")]
        Config914 = 914,

        [ValorPadrao("0")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Numero")]
        [ItemDrop("")]
        [Ordem(23)]
        [Grupo("40-Ponto de Venda")]
        [Description("Qtd. Sessões Simultâneas")]
        Config915 = 915,

        [ValorPadrao("XYZ")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Texto")]
        [ItemDrop("")]
        [Ordem(13)]
        [Grupo("40-Ponto de Venda")]
        [Description("Codigo Único de Ticket")]
        Config916 = 916,

        [ValorPadrao("*** Reclamações sobre Tickets apenas no momento da Compra")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Texto")]
        [ItemDrop("")]
        [Ordem(14)]
        [Grupo("40-Ponto de Venda")]
        [Description("Rodapé de Impressão do Ticket")]
        Config917 = 917,

        [ValorPadrao("1")]
        [VMinPadrao(0)]
        [VMaxPadrao(1)]
        [TpControle(1)]
        [TpTxt("Numero")]
        [ItemDrop("Não|Sim")]
        [Ordem(18)]
        [Grupo("40-Ponto de Venda")]
        [Description("Preencher Valor de Produto Zerado")]
        Config918 = 918,

        [ValorPadrao("100")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Texto")]
        [ItemDrop("")]
        [Ordem(21)]
        [Grupo("40-Ponto de Venda")]
        [Description("Cod Produto Percentual Garçon")]
        Config919 = 919,

        [ValorPadrao("")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Texto")]
        [ItemDrop("")]
        [Ordem(20)]
        [Grupo("40-Ponto de Venda")]
        [Description("Cod Produto Couvert")]
        Config920 = 920,

        [ValorPadrao("60")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Texto")]
        [ItemDrop("")]
        [Ordem(24)]
        [Grupo("40-Ponto de Venda")]
        [Description("Qtde. Máxima de Busca")]
        Config921 = 921,

        [ValorPadrao("01")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Texto")]
        [ItemDrop("")]
        [Ordem(22)]
        [Grupo("40-Ponto de Venda")]
        [Description("Cod Produto Taxa Entrega")]
        Config922 = 922,

        [ValorPadrao("1")]
        [VMinPadrao(0)]
        [VMaxPadrao(5)]
        [TpControle(1)]
        [TpTxt("Numero")]
        [ItemDrop("")]
        [Ordem(2)]
        [Grupo("40-Ponto de Venda")]
        [Description("Quantidade de Vias de Impressão de Valores")]
        Config923 = 923,

        [ValorPadrao("5")]
        [VMinPadrao(-1)]
        [VMaxPadrao(-10)]
        [TpControle(-1)]
        [TpTxt("Numero")]
        [ItemDrop("Não Exibir Resumo|Aguardar Confirmação|1 Seg.|2 Seg.|3 Seg.|4 Seg.|5 Seg.|6 Seg.|7 Seg.|8 Seg.|9 Seg.|10 Seg.")]
        [Ordem(2)]
        [Grupo("40-Ponto de Venda")]
        [Description("Tempo de Exibição do Resumo de Pagamento (Segundos)")]
        Config924 = 924,

        [ValorPadrao("1")]
        [VMinPadrao(0)]
        [VMaxPadrao(2)]
        [TpControle(1)]
        [TpTxt("Numero")]
        [ItemDrop("Sempre Imprimir|Nunca Imprimir|Verificar Permissão")]
        [Ordem(25)]
        [Grupo("40-Ponto de Venda")]
        [Description("Impressão de Resumo de Sessão no Fechamento do Caixa")]
        Config925 = 925,

        [ValorPadrao("")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Texto")]
        [ItemDrop("")]
        [Ordem(26)]
        [Grupo("40-Ponto de Venda")]
        [Description("Local para Compartilhamento de Fila de Espera")]
        Config926 = 926,

        [ValorPadrao("999")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Numero")]
        [ItemDrop("")]
        [Ordem(27)]
        [Grupo("40-Ponto de Venda")]
        [Description("Sequencial Máximo da Fila")]
        Config927 = 927,

        [ValorPadrao("0")]
        [VMinPadrao(0)]
        [VMaxPadrao(1)]
        [TpControle(1)]
        [TpTxt("Texto")]
        [ItemDrop("Leve|Completa (Depuração)")]
        [Ordem(27)]
        [Grupo("40-Ponto de Venda")]
        [Description("Modelo de Gravação de Log")]
        Config928 = 928,

        [ValorPadrao("0")]
        [VMinPadrao(0)]
        [VMaxPadrao(1)]
        [TpControle(1)]
        [TpTxt("Numero")]
        [ItemDrop("Não|Sim")]
        [Ordem(1)]
        [Grupo("40-Ponto de Venda")]
        [Description("Abertura Gaveta antes Movimentação de Valores")]
        Config929 = 929,

        [ValorPadrao("0")]
        [VMinPadrao(0)]
        [VMaxPadrao(3)]
        [TpControle(1)]
        [TpTxt("Numero")]
        [ItemDrop("0 - Por Sessão e Tipo de Movimento|1 - Por Sessão|2 - Sangria e Despesa Geral|3 - Sequencial Geral")]
        [Ordem(1)]
        [Grupo("40-Ponto de Venda")]
        [Description("Tipo de Nro Sequencial de Movimento de Valores")]
        Config930 = 930,

        [ValorPadrao("0")]
        [VMinPadrao(0)]
        [VMaxPadrao(1)]
        [TpControle(1)]
        [TpTxt("Numero")]
        [ItemDrop("Facilitado (Não permite diferenças em pagamentos eletrônicos)|Completo (Permite diferenças em formas de pagamento eletrônicas)")]
        [Ordem(28)]
        [Grupo("40-Ponto de Venda")]
        [Description("Tipo de Fechamento de Sessão")]
        Config931 = 931,

        [ValorPadrao("1")]
        [VMinPadrao(0)]
        [VMaxPadrao(1)]
        [TpControle(1)]
        [TpTxt("Numero")]
        [ItemDrop("Pequeno|Grande")]
        [Ordem(0)]
        [Grupo("40-Ponto de Venda")]
        [Description("Modelo de Impressão de Valores")]
        Config932 = 932,

        [ValorPadrao("0")]
        [VMinPadrao(0)]
        [VMaxPadrao(2)]
        [TpControle(1)]
        [TpTxt("Texto")]
        [ItemDrop("Padrão|Atualizar item|Agrupar por código")]
        [Ordem(29)]
        [Grupo("40-Ponto de Venda")]
        [Description("Tipo de adição do produto")]
        Config934 = 934,

        [ValorPadrao("1")]
        [VMinPadrao(0)]
        [VMaxPadrao(5)]
        [TpControle(1)]
        [TpTxt("Numero")]
        [ItemDrop("")]
        [Ordem(2)]
        [Grupo("40-Ponto de Venda")]
        [Description("Quantidade de Vias de Impressão do Cupom")]
        Config935 = 935,

        [ValorPadrao("1")]
        [VMinPadrao(0)]
        [VMaxPadrao(2)]
        [TpControle(1)]
        [TpTxt("Numero")]
        [ItemDrop("Número do Cartão|Numero do Cartão + Senha|Documento do Cliente da Venda")]
        [Ordem(1)]
        [Grupo("81-Cartão Fidelidade")]
        [Description("Modelo de Autenticação")]
        Config1000 = 1000,

        [ValorPadrao("0")]
        [VMinPadrao(0)]
        [VMaxPadrao(1)]
        [TpControle(1)]
        [TpTxt("Numero")]
        [ItemDrop("Não Solicitar|Solicitar")]
        [Ordem(3)]
        [Grupo("81-Cartão Fidelidade")]
        [Description("Odômetro e Motorista")]
        Config1001 = 1001,

        [ValorPadrao("0")]
        [VMinPadrao(0)]
        [VMaxPadrao(4)]
        [TpControle(1)]
        [TpTxt("Numero")]
        [ItemDrop("Não Imprimir|Padrão|Padrão+Parcelamento|Simples|Simples + Parcelamento")]
        [Ordem(2)]
        [Grupo("81-Cartão Fidelidade")]
        [Description("Modelo de Promissória")]
        Config1002 = 1002,

        [ValorPadrao("1")]
        [VMinPadrao(0)]
        [VMaxPadrao(1)]
        [TpControle(1)]
        [TpTxt("Numero")]
        [ItemDrop("Desabilitado|Habilitado")]
        [Ordem(4)]
        [Grupo("81-Cartão Fidelidade")]
        [Description("Validar Limite do Cartão")]
        Config1003 = 1003,

        [ValorPadrao("90")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Numero")]
        [ItemDrop("")]
        [Ordem(5)]
        [Grupo("81-Cartão Fidelidade")]
        [Description("Dias de Histórico")]
        Config1004 = 1004,

        [ValorPadrao("1")]
        [VMinPadrao(0)]
        [VMaxPadrao(1)]
        [TpControle(1)]
        [TpTxt("Numero")]
        [ItemDrop("Desabilitado|Habilitado")]
        [Ordem(8)]
        [Grupo("81-Cartão Fidelidade")]
        [Description("Estorno em outra Forma de Pagamento")]
        Config1007 = 1007,

        [ValorPadrao("0")]
        [VMinPadrao(0)]
        [VMaxPadrao(1)]
        [TpControle(1)]
        [TpTxt("Numero")]
        [ItemDrop("Padrão (Agrupado)|Baixa Individual")]
        [Ordem(9)]
        [Grupo("81-Cartão Fidelidade")]
        [Description("Tipo de Baixa de Pendências")]
        Config1008 = 1008,

        [ValorPadrao("")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Texto")]
        [ItemDrop("")]
        [Ordem(0)]
        [Grupo("90-Servidor de Auto Postos")]
        [Description("Porta COM ou IP")]
        Config1100 = 1100,

        [ValorPadrao("")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Texto")]
        [ItemDrop("")]
        [Ordem(1)]
        [Grupo("90-Servidor de Auto Postos")]
        [Description("Velocidade ou Porta TCP")]
        Config1101 = 1101,

        [ValorPadrao("500")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Numero")]
        [ItemDrop("")]
        [Ordem(2)]
        [Grupo("90-Servidor de Auto Postos")]
        [Description("Delay Comando (ms)")]
        Config1102 = 1102,

        [ValorPadrao("500")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Numero")]
        [ItemDrop("")]
        [Ordem(3)]
        [Grupo("90-Servidor de Auto Postos")]
        [Description("WaitTime")]
        Config1103 = 1103,

        [ValorPadrao("1")]
        [VMinPadrao(0)]
        [VMaxPadrao(1)]
        [TpControle(1)]
        [TpTxt("Numero")]
        [ItemDrop("CompanyTec|Saurus")]
        [Ordem(4)]
        [Grupo("90-Servidor de Auto Postos")]
        [Description("Comunicação")]
        Config1104 = 1104,

        [ValorPadrao("")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Texto")]
        [ItemDrop("")]
        [Ordem(6)]
        [Grupo("90-Servidor de Auto Postos")]
        [Description("Senha de Consumo para Integração LMC")]
        Config1105 = 1105,

        [ValorPadrao("0")]
        [VMinPadrao(0)]
        [VMaxPadrao(1)]
        [TpControle(1)]
        [TpTxt("Numero")]
        [ItemDrop("Não|Sim")]
        [Ordem(5)]
        [Grupo("90-Servidor de Auto Postos")]
        [Description("Log Concentrador")]
        Config1106 = 1106,

        [ValorPadrao("0")]
        [VMinPadrao(0)]
        [VMaxPadrao(2)]
        [TpControle(1)]
        [TpTxt("Numero")]
        [ItemDrop("Abastecimento PAF-ECF|Abastecimento Simples|Abastecimento Simples com Identificação")]
        [Ordem(7)]
        [Grupo("90-Servidor de Auto Postos")]
        [Description("Tipo de Comando para Captura de Abastecimentos")]
        Config1107 = 1107,

        [ValorPadrao("0")]
        [VMinPadrao(0)]
        [VMaxPadrao(1)]
        [TpControle(1)]
        [TpTxt("Numero")]
        [ItemDrop("Sim|Não")]
        [Ordem(8)]
        [Grupo("90-Servidor de Auto Postos")]
        [Description("Preenchimento de Encerrantes no Fechamento e Abertura")]
        Config1108 = 1108,

        [ValorPadrao("0")]
        [VMinPadrao(0)]
        [VMaxPadrao(1)]
        [TpControle(1)]
        [TpTxt("Numero")]
        [ItemDrop("Obrigatório|Opcional")]
        [Ordem(9)]
        [Grupo("90-Servidor de Auto Postos")]
        [Description("Bloqueio de Pista no Fechamento")]
        Config1109 = 1109,

        [ValorPadrao("0")]
        [VMinPadrao(0)]
        [VMaxPadrao(1)]
        [TpControle(1)]
        [TpTxt("Numero")]
        [ItemDrop("Não|Sim")]
        [Ordem(9)]
        [Grupo("90-Servidor de Auto Postos")]
        [Description("Exibir Abastecidas do Vendedor")]
        Config1110 = 1110,

        [ValorPadrao("0")]
        [VMinPadrao(0)]
        [VMaxPadrao(1)]
        [TpControle(1)]
        [TpTxt("Numero")]
        [ItemDrop("Não|Sim")]
        [Ordem(7)]
        [Grupo("90-Servidor de Auto Postos")]
        [Description("Bloquear Bicos na Inicialização")]
        Config1111 = 1111,

        [ValorPadrao("1")]
        [VMinPadrao(0)]
        [VMaxPadrao(1)]
        [TpControle(1)]
        [TpTxt("Texto")]
        [ItemDrop("Opcional|Obrigatório")]
        [Ordem(2)]
        [Grupo("41-Troca de Mercadoria")]
        [Description("Nome do Cliente")]
        Config1200 = 1200,

        [ValorPadrao("0")]
        [VMinPadrao(0)]
        [VMaxPadrao(1)]
        [TpControle(1)]
        [TpTxt("Texto")]
        [ItemDrop("Opcional|Obrigatório")]
        [Ordem(3)]
        [Grupo("41-Troca de Mercadoria")]
        [Description("Telefone do Cliente")]
        Config1201 = 1201,

        [ValorPadrao("0")]
        [VMinPadrao(0)]
        [VMaxPadrao(1)]
        [TpControle(1)]
        [TpTxt("Texto")]
        [ItemDrop("Opcional|Obrigatório")]
        [Ordem(4)]
        [Grupo("41-Troca de Mercadoria")]
        [Description("Email do Cliente")]
        Config1202 = 1202,

        [ValorPadrao("30")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Numero")]
        [ItemDrop("30")]
        [Ordem(1)]
        [Grupo("41-Troca de Mercadoria")]
        [Description("Validade do Vale Troca (Dias)")]
        Config1203 = 1203,

        [ValorPadrao("")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Texto")]
        [ItemDrop("")]
        [Ordem(1)]
        [Grupo("88-PicPay")]
        [Description("PicPay Token")]
        Config1204 = 1204,

        [ValorPadrao("XXX")]
        [VMinPadrao(0)]
        [VMaxPadrao(0)]
        [TpControle(0)]
        [TpTxt("Texto")]
        [ItemDrop("")]
        [Ordem(2)]
        [Grupo("88-PicPay")]
        [Description("PicPay Seller Token")]
        Config1205 = 1205
    }
}