// <auto-generated />
using System;
using ISync.Classes.Core.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ISync.Migrations.Cadastro
{
    [DbContext(typeof(CadastroContext))]
    [Migration("20250804202635_CriarTabelasCadastro")]
    partial class CriarTabelasCadastro
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ISync.Entidades.Cadastros.EmpresaDado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CMun")
                        .HasColumnType("int");

                    b.Property<string>("Cep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Crt")
                        .HasColumnType("int");

                    b.Property<string>("Doc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fant")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Site")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SysDInsert")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SysDUpdate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SysIsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XBairro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCpl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XLgr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XMun")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XNome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tbEmpresaDados", (string)null);
                });

            modelBuilder.Entity("ISync.Entidades.Cadastros.Imposto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CBenef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Cfop")
                        .HasColumnType("int");

                    b.Property<string>("CofinsCst")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CofinsPercVUnidCofins")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DescImposto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("EcfAliq")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("IcmsCst")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IcmsModBc")
                        .HasColumnType("int");

                    b.Property<int>("IcmsModBcSt")
                        .HasColumnType("int");

                    b.Property<int>("IcmsMotDesIcms")
                        .HasColumnType("int");

                    b.Property<decimal>("IcmsPBcOp")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IcmsPCredSn")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IcmsPIcms")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IcmsPIcmsSt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IcmsPMvaVUnidSt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IcmsPRedBc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IcmsPredBcSt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IcmsPredSn")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("IcmsUfSt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PisCst")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PisPercVUnidPis")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("SysDInsert")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SysDUpdate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SysIsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("tbProdutoImpostos", (string)null);
                });

            modelBuilder.Entity("ISync.Entidades.Cadastros.NaturezaOperacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Calcular")
                        .HasColumnType("int");

                    b.Property<string>("DescNatureza")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ImpostoId")
                        .HasColumnType("int");

                    b.Property<string>("IndOperacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IndStatus")
                        .HasColumnType("int");

                    b.Property<string>("InfAdc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SysDInsert")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SysDUpdate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SysIsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("UfDest")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UfOrigem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ImpostoId");

                    b.ToTable("tbNaturezaOperacao", (string)null);
                });

            modelBuilder.Entity("ISync.Entidades.Cadastros.Parceiro.Parceiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CPFCNPJ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DNasc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<string>("Fantasia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IERG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IndIEDest")
                        .HasColumnType("int");

                    b.Property<string>("InfInterno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InfOperador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Limite")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Saldo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("SysDInsert")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SysDUpdate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SysIsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("TpCadastro")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("tbCadastroDados", (string)null);
                });

            modelBuilder.Entity("ISync.Entidades.Cadastros.Parceiro.ParceiroEndereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CMun")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CPais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CUF")
                        .HasColumnType("int");

                    b.Property<int>("CadastroId")
                        .HasColumnType("int");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IERG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IndIEDest")
                        .HasColumnType("int");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SysDInsert")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SysDUpdate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SysIsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XMun")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CadastroId");

                    b.ToTable("ParceiroEndereco");
                });

            modelBuilder.Entity("ISync.Entidades.Cadastros.ProdutoDado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CODIF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CProdANP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescANP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescMedida")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescProduto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ImpostoId")
                        .HasColumnType("int");

                    b.Property<int>("IndStatus")
                        .HasColumnType("int");

                    b.Property<string>("InfAdic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ncm")
                        .HasColumnType("int");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PGLP")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PGNi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PGNn")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("SysDInsert")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SysDUpdate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SysIsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("VProd")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("tbProdutoDados", (string)null);
                });

            modelBuilder.Entity("ISync.Entidades.Cadastros.NaturezaOperacao", b =>
                {
                    b.HasOne("ISync.Entidades.Cadastros.Imposto", "Imposto")
                        .WithMany()
                        .HasForeignKey("ImpostoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Imposto");
                });

            modelBuilder.Entity("ISync.Entidades.Cadastros.Parceiro.ParceiroEndereco", b =>
                {
                    b.HasOne("ISync.Entidades.Cadastros.Parceiro.Parceiro", "Cadastro")
                        .WithMany("Enderecos")
                        .HasForeignKey("CadastroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cadastro");
                });

            modelBuilder.Entity("ISync.Entidades.Cadastros.Parceiro.Parceiro", b =>
                {
                    b.Navigation("Enderecos");
                });
#pragma warning restore 612, 618
        }
    }
}
